### ISSUE TITLE
[BUG]: Overlay missing in playlist

### ISSUE THREAD

**Issue by pixel-fabian** [Sommerwiesel/invidious#10]
**Describe the bug**
If you use playlists, the overlays are missing. This way you cant see which videos you have already watched and more importantly you cant remove videos from the list.

**To Reproduce**
1. Create a playlist
2. Add some videos
3. Open the playlist

**Screenshots**
Comparison to the default dark theme. Looks like some CSS is missing.
![comparison](https://github.com/Sommerwiesel/invidious/assets/82926714/5ddacbaa-b680-41eb-aa90-e4fa3ef6485a)

**Comment by Sommerwiesel** [comment]
Can confirm this is a bug with my custom CSS.
Will fix it this evening.
Thanks for bringing this to my attention

**Comment by Sommerwiesel** [comment]
Sorry something came up and I need some additional time to fix this. Will change to Invidious default CSS until I find the time to make my CSS work again.

**Comment by k0zyrev** [comment]
While you're working on your custom CSS, could you consider not removing "watch on youtube" link from the video pages? It really comes in handy sometimes (for example: when I want to leave a comment, when I want to go to live translation, when occasionally video doesn't work), and it's quite noticeable when it's missing.

**Comment by Sommerwiesel** [comment]
> While you're working on your custom CSS, could you consider not removing "watch on youtube" link from the video pages? It really comes in handy sometimes (for example: when I want to leave a comment, when I want to go to live translation, when occasionally video doesn't work), and it's quite noticeable when it's missing.

Sure why not, while I personally don't think that you should ever use that link because it throws any benefit of using Invidious and it's added privacy right out of the window, it is after all, your decision to make.

Haven't gotten to fixing my css yet, much more important things on my todo right now. Default Invidious CSS stays active.

**Comment by Sommerwiesel** [comment]
Have decided to not use a custom css anymore.
The Invidious team is constantly adding new features and updating the layout.
Using a custom css will only break funtionality and thus, my site will now use the default.

Closed
